services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: backend:latest
    ports:
      - "7175:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
